"""Add soil_sensor_devices table

Revision ID: 032fb0fd0070
Revises: 9870e0d347d6
Create Date: 2025-09-14 19:46:09.796378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032fb0fd0070'
down_revision: Union[str, Sequence[str], None] = '9870e0d347d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('soil_data_sensor_id_fkey'), 'soil_data', type_='foreignkey')
    op.create_foreign_key(None, 'soil_data', 'soil_sensor_devices', ['sensor_id'], ['sensor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'soil_data', type_='foreignkey')
    op.create_foreign_key(op.f('soil_data_sensor_id_fkey'), 'soil_data', 'soil_sensor_devices', ['sensor_id'], ['sensor_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
