"""feat: farmer_id type to UUID

Revision ID: 3671269a4943
Revises: 673f5a72c2cb
Create Date: 2025-09-09 09:51:04.620782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3671269a4943'
down_revision: Union[str, Sequence[str], None] = '673f5a72c2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')

    # Drop constraints first
    op.drop_constraint("farming_history_farmer_id_fkey", "farming_history", type_="foreignkey")
    op.drop_constraint("farming_schedule_farmer_id_fkey", "farming_schedule", type_="foreignkey")

    # Change farmer table IDs
    op.alter_column(
        "farmer",
        "farmer_id",
        type_=sa.dialects.postgresql.UUID(as_uuid=True),
        postgresql_using="gen_random_uuid()"
    )

    # Change child tables
    op.alter_column(
        "farming_history",
        "farmer_id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.dialects.postgresql.UUID(as_uuid=True),
        postgresql_using="gen_random_uuid()",
        existing_nullable=False
    )
    op.alter_column(
        "farming_schedule",
        "farmer_id",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.dialects.postgresql.UUID(as_uuid=True),
        postgresql_using="gen_random_uuid()",
        existing_nullable=False
    )

    # Recreate constraints
    op.create_foreign_key(
        "farming_history_farmer_id_fkey",
        "farming_history", "farmer",
        ["farmer_id"], ["farmer_id"]
    )
    op.create_foreign_key(
        "farming_schedule_farmer_id_fkey",
        "farming_schedule", "farmer",
        ["farmer_id"], ["farmer_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("farming_history_farmer_id_fkey", "farming_history", type_="foreignkey")
    op.drop_constraint("farming_schedule_farmer_id_fkey", "farming_schedule", type_="foreignkey")

    # Convert child tables back to VARCHAR(20)
    op.alter_column(
        "farming_history",
        "farmer_id",
        existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
        type_=sa.VARCHAR(length=20),
        postgresql_using="farmer_id::text",
        existing_nullable=False
    )

    op.alter_column(
        "farming_schedule",
        "farmer_id",
        existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
        type_=sa.VARCHAR(length=20),
        postgresql_using="farmer_id::text",
        existing_nullable=False
    )

    # Convert farmer table back to VARCHAR(20)
    op.alter_column(
        "farmer",
        "farmer_id",
        existing_type=sa.dialects.postgresql.UUID(as_uuid=True),
        type_=sa.VARCHAR(length=20),
        postgresql_using="farmer_id::text",
        existing_nullable=False
    )

    # Recreate the foreign key constraints
    op.create_foreign_key(
        "farming_history_farmer_id_fkey",
        "farming_history", "farmer",
        ["farmer_id"], ["farmer_id"]
    )
    op.create_foreign_key(
        "farming_schedule_farmer_id_fkey",
        "farming_schedule", "farmer",
        ["farmer_id"], ["farmer_id"]
    )
    # ### end Alembic commands ###
