"""Add Soil Forecast Tables

Revision ID: 4f7644e77e38
Revises: e8026bb3753f
Create Date: 2026-01-04 14:41:44.294809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7644e77e38'
down_revision: Union[str, Sequence[str], None] = 'e8026bb3753f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil_forecasts',
    sa.Column('forecast_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('planting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('approach_used', sa.String(length=20), nullable=True),
    sa.Column('baseline_reading', sa.JSON(), nullable=True),
    sa.Column('forecast_data', sa.JSON(), nullable=False),
    sa.Column('weekly_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_realignment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('realignment_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farmer.farmer_id'], ),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_table('soil_readings',
    sa.Column('reading_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('forecast_id', sa.UUID(), nullable=True),
    sa.Column('sensor_id', sa.UUID(), nullable=True),
    sa.Column('reading_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('nitrogen_ppm', sa.JSON(), nullable=True),
    sa.Column('phosphorus_ppm', sa.JSON(), nullable=True),
    sa.Column('potassium_meq', sa.JSON(), nullable=True),
    sa.Column('ph', sa.JSON(), nullable=True),
    sa.Column('soil_moisture_pct', sa.JSON(), nullable=True),
    sa.Column('organic_matter_pct', sa.JSON(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('health_category', sa.String(length=20), nullable=True),
    sa.Column('raw_readings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farmer.farmer_id'], ),
    sa.ForeignKeyConstraint(['forecast_id'], ['soil_forecasts.forecast_id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['soil_sensor_devices.sensor_id'], ),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_table('forecast_realignments',
    sa.Column('realignment_id', sa.UUID(), nullable=False),
    sa.Column('forecast_id', sa.UUID(), nullable=False),
    sa.Column('reading_id', sa.UUID(), nullable=False),
    sa.Column('realignment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('week_of_realignment', sa.Integer(), nullable=False),
    sa.Column('deviations', sa.JSON(), nullable=False),
    sa.Column('corrections_applied', sa.JSON(), nullable=False),
    sa.Column('required_reforecast', sa.Boolean(), nullable=True),
    sa.Column('forecast_before', sa.JSON(), nullable=True),
    sa.Column('forecast_after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['soil_forecasts.forecast_id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['soil_readings.reading_id'], ),
    sa.PrimaryKeyConstraint('realignment_id')
    )
    op.drop_index(op.f('ix_user_user_id'), table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index(op.f('ix_user_user_id'), 'users', ['user_id'], unique=False)
    op.drop_table('forecast_realignments')
    op.drop_table('soil_readings')
    op.drop_table('soil_forecasts')
    # ### end Alembic commands ###
