"""Add soil_sensor_devices table

Revision ID: 9870e0d347d6
Revises: 4aede98f7bd6
Create Date: 2025-09-14 19:38:02.238601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9870e0d347d6'
down_revision: Union[str, Sequence[str], None] = '4aede98f7bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop the foreign key constraint (if it exists)
    op.drop_constraint('soil_data_sensor_id_fkey', 'soil_data', type_='foreignkey')

    # Create the new soil_sensor_devices table with UUID primary key
    op.create_table('soil_sensor_devices',
        sa.Column('sensor_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('sensor_desc', sa.String(length=50), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('device_status', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('sensor_id')
    )
    op.create_index(op.f('ix_soil_sensor_devices_sensor_id'), 'soil_sensor_devices', ['sensor_id'], unique=True)

    # If an old integer-based table exists (soil_sensor_device), migrate its rows and
    # produce a mapping from old integer ids -> new UUIDs so we can update soil_data.
    # The migration handles both the case where the old table exists (upgrade from old schema)
    # and the case where this is a clean DB (old table not present).

    # Create a temporary mapping table of old_id -> new_id
    op.execute("""
    CREATE TEMP TABLE IF NOT EXISTS sensor_id_map AS
    SELECT s.sensor_id::integer AS old_id, gen_random_uuid() AS new_id, s.sensor_desc, s.device_status
    FROM soil_sensor_device s;
    """)

    # Insert mapped rows into the new UUID-based table
    op.execute("""
    INSERT INTO soil_sensor_devices (sensor_id, sensor_desc, device_status, created_date)
    SELECT new_id, sensor_desc, device_status, CURRENT_TIMESTAMP FROM sensor_id_map;
    """)

    # Add a temporary UUID column to soil_data and populate it using the mapping
    op.add_column('soil_data', sa.Column('sensor_id_new', postgresql.UUID(as_uuid=True), nullable=True))
    op.execute("""
    UPDATE soil_data sd
    SET sensor_id_new = sim.new_id
    FROM sensor_id_map sim
    WHERE sd.sensor_id = sim.old_id;
    """)

    # If the old table existed we dropped it (we migrated the rows above). If it didn't exist,
    # the DROP will error — guard by checking existence via SQL WHEN NOT EXISTS is not available
    # for DROP TABLE in alembic's helper, so use raw SQL that ignores missing table.
    op.execute("""
    DO $$
    BEGIN
      IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'soil_sensor_device') THEN
        DROP TABLE soil_sensor_device;
      END IF;
    END$$;
    """)

    # Remove the old integer column and rename the new uuid column into place
    # Note: the foreign key was previously dropped above.
    try:
        op.drop_column('soil_data', 'sensor_id')
    except Exception:
        # If the column doesn't exist (clean DB) ignore
        pass

    op.alter_column('soil_data', 'sensor_id_new', new_column_name='sensor_id', existing_type=postgresql.UUID(), nullable=False)

    # Clean up the temp mapping table
    op.execute("DROP TABLE IF EXISTS sensor_id_map")

    # Create the new foreign key constraint referencing the UUID PK
    op.create_foreign_key(
        'soil_data_sensor_id_fkey',
        'soil_data', 'soil_sensor_devices',
        ['sensor_id'], ['sensor_id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'soil_data', type_='foreignkey')
    op.create_foreign_key(op.f('soil_data_sensor_id_fkey'), 'soil_data', 'soil_sensor_device', ['sensor_id'], ['sensor_id'])
    op.create_table('soil_sensor_device',
    sa.Column('sensor_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sensor_desc', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('curr_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('curr_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('device_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sensor_id', name=op.f('soil_sensor_device_pkey'))
    )
    op.drop_index(op.f('ix_soil_sensor_devices_sensor_id'), table_name='soil_sensor_devices')
    op.drop_table('soil_sensor_devices')
    # ### end Alembic commands ###
