"""Add soil_sensor_devices table

Revision ID: 9870e0d347d6
Revises: 4aede98f7bd6
Create Date: 2025-09-14 19:38:02.238601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9870e0d347d6'
down_revision: Union[str, Sequence[str], None] = '4aede98f7bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First drop the foreign key constraint
    op.drop_constraint('soil_data_sensor_id_fkey', 'soil_data', type_='foreignkey')
    
    # Create the new table
    op.create_table('soil_sensor_devices',
        sa.Column('sensor_id', sa.UUID(), nullable=False),
        sa.Column('sensor_desc', sa.String(length=50), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('device_status', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('sensor_id')
    )
    op.create_index(op.f('ix_soil_sensor_devices_sensor_id'), 'soil_sensor_devices', ['sensor_id'], unique=True)
    
    # Copy data from old table to new table if needed
    # Note: This is a simplified example. You might need to adjust the data migration part
    # based on your actual data structure and requirements.
    op.execute('''
        INSERT INTO soil_sensor_devices (sensor_id, sensor_desc, device_status, created_date)
        SELECT 
            gen_random_uuid(),  -- Generate new UUIDs for the new table
            sensor_desc, 
            device_status, 
            CURRENT_TIMESTAMP  -- Set created_date to current timestamp
        FROM soil_sensor_device
    ''')
    
    # Drop the old table
    op.drop_table('soil_sensor_device')
    
    # Create the new foreign key constraint
    op.create_foreign_key(
        'soil_data_sensor_id_fkey',
        'soil_data', 'soil_sensor_devices',
        ['sensor_id'], ['sensor_id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'soil_data', type_='foreignkey')
    op.create_foreign_key(op.f('soil_data_sensor_id_fkey'), 'soil_data', 'soil_sensor_device', ['sensor_id'], ['sensor_id'])
    op.create_table('soil_sensor_device',
    sa.Column('sensor_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sensor_desc', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('curr_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('curr_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('device_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sensor_id', name=op.f('soil_sensor_device_pkey'))
    )
    op.drop_index(op.f('ix_soil_sensor_devices_sensor_id'), table_name='soil_sensor_devices')
    op.drop_table('soil_sensor_devices')
    # ### end Alembic commands ###
