"""initial migration

Revision ID: e8026bb3753f
Revises: 
Create Date: 2025-10-18 18:09:01.824926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8026bb3753f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season',
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('soil_sensor_devices',
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('sensor_desc', sa.String(length=100), nullable=False),
    sa.Column('device_status', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('sensor_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('weather_data',
    sa.Column('weather_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_temp', sa.Float(), nullable=False),
    sa.Column('min_temp', sa.Float(), nullable=False),
    sa.Column('rainfall', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_direct', sa.CHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('weather_id')
    )
    op.create_table('farmer',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), server_default='Pacol,Naga City', nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('farmer_id')
    )
    op.create_index(op.f('ix_farmer_first_name'), 'farmer', ['first_name'], unique=False)
    op.create_index(op.f('ix_farmer_last_name'), 'farmer', ['last_name'], unique=False)
    op.create_table('rice_variety',
    sa.Column('rice_variety_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('rice_name', sa.String(length=100), nullable=False),
    sa.Column('growth_duration', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.season_id'], ),
    sa.PrimaryKeyConstraint('rice_variety_id')
    )
    op.create_table('soil_data',
    sa.Column('soil_id', sa.UUID(), nullable=False),
    sa.Column('datetimestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('soil_moisture', sa.Float(), nullable=False),
    sa.Column('soil_ph', sa.Float(), nullable=False),
    sa.Column('nitrogen_level', sa.Float(), nullable=False),
    sa.Column('phosphorus_level', sa.Float(), nullable=False),
    sa.Column('potassium_level', sa.Float(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['soil_sensor_devices.sensor_id'], ),
    sa.PrimaryKeyConstraint('soil_id')
    )
    op.create_table('farming_history',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('history_date', sa.Date(), nullable=True),
    sa.Column('history_title', sa.String(length=100), nullable=True),
    sa.Column('yields', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.farmer_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('soil_analysis',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('soil_id', sa.UUID(), nullable=False),
    sa.Column('analysis_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('soil_health_summary', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['soil_id'], ['soil_data.soil_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_table('variety_suggestion',
    sa.Column('variety_sugg_id', sa.UUID(), nullable=False),
    sa.Column('rice_variety_id', sa.UUID(), nullable=False),
    sa.Column('feedback', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rice_variety_id'], ['rice_variety.rice_variety_id'], ),
    sa.PrimaryKeyConstraint('variety_sugg_id')
    )
    op.create_table('farm_dataset',
    sa.Column('farm_dataset_id', sa.UUID(), nullable=False),
    sa.Column('rice_variety_id', sa.UUID(), nullable=False),
    sa.Column('weather_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('planting_date_start', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['soil_analysis.analysis_id'], ),
    sa.ForeignKeyConstraint(['rice_variety_id'], ['rice_variety.rice_variety_id'], ),
    sa.ForeignKeyConstraint(['weather_id'], ['weather_data.weather_id'], ),
    sa.PrimaryKeyConstraint('farm_dataset_id')
    )
    op.create_table('farming_schedule',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('farm_dataset_id', sa.UUID(), nullable=False),
    sa.Column('farmer_feedback', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['farm_dataset_id'], ['farm_dataset.farm_dataset_id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.farmer_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('task',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('priority_level', sa.CHAR(length=1), nullable=False),
    sa.Column('feedback', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['farming_schedule.schedule_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('farming_schedule')
    op.drop_table('farm_dataset')
    op.drop_table('variety_suggestion')
    op.drop_table('soil_analysis')
    op.drop_table('farming_history')
    op.drop_table('soil_data')
    op.drop_table('rice_variety')
    op.drop_index(op.f('ix_farmer_last_name'), table_name='farmer')
    op.drop_index(op.f('ix_farmer_first_name'), table_name='farmer')
    op.drop_table('farmer')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('soil_sensor_devices')
    op.drop_table('season')
    # ### end Alembic commands ###
